services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sindeuda
      - POSTGRES_PASSWORD=sindeuda
      - POSTGRES_DB=sindeuda
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge