version: '3.9'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sindeuda
      POSTGRES_PASSWORD: sindeuda
      POSTGRES_DB: sindeuda
    volumes:
      - ./postgres-data:/var/lib/postgresql/data