"""Initial migration

Revision ID: baaba1c92e3a
Revises: 
Create Date: 2024-03-20 16:24:30.903416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baaba1c92e3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('account',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('card_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('bank', sa.VARCHAR(length=30), nullable=False),
    sa.Column('balance', sa.INTEGER(), nullable=False),
    sa.Column('credit_limit', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('expense_budget', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('category')
    op.drop_table('account')
    op.drop_table('user')
    # ### end Alembic commands ###
